spring:
  application:
    name: cache
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  # sql:
  #   init:
  #     mode: always
